### ISSUE TITLE
Confused and crazy balancing

### ISSUE THREAD

**Issue by ZephDio** [BokChoyWithSoy/BokChoyItemPack#1]
Hey dude , thanks for the mod ,
I was wondering if it is possible to add a config file for your items since I really feel like confuse and crazy is an amazing item but way too good.
Thanks for your time

**Comment by BokChoyWithSoy** [comment]
I was planning to add a config, should be out soonish. The item was going to be nerfed to 40% next patch.

**Comment by ZephDio** [comment]
Thank you sire !

**Comment by BokChoyWithSoy** [comment]
Heya, I know its a bit late but the configs have been added in the recent release.
